// Auto-generated by scripts/generate-sprite.ts
// Do not edit manually

export type IconName =
  | 'date-and-location-mobile-arrow'
  | 'hamburger'
  | 'instagram'
  | 'facebook'
  | 'linkedin'
  | 'twitter'
  | 'date-and-location-arrow'
  | 'breakout'
  | 'devfest-logo'
  | 'techies-assemble'
  | 'learn-listen-repeat'
  | 'close'
  | 'carousel-right'
  | 'gdg-bag'
  | 'ticket-arrow'
  | 'network'
  | 'carousel-left'
  | 'nav-logo'
  | 'five-days';

export const iconNames: IconName[] = [
  'date-and-location-mobile-arrow',
  'hamburger',
  'instagram',
  'facebook',
  'linkedin',
  'twitter',
  'date-and-location-arrow',
  'breakout',
  'devfest-logo',
  'techies-assemble',
  'learn-listen-repeat',
  'close',
  'carousel-right',
  'gdg-bag',
  'ticket-arrow',
  'network',
  'carousel-left',
  'nav-logo',
  'five-days',
];
