/* eslint-disable simple-import-sort/imports */
/* eslint-disable @next/next/no-img-element */

import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const customFont = localFont({
  src: "./fonts/Akira.otf",
  variable: "--font-custom",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customFont.variable} h-screen bg-[#FFFAEB] antialiased`}
      >
        <img
          src="/lanyard.webp"
          alt="Lanyard"
          className="absolute top-[-50px] left-1/2 hidden -translate-x-1/2 lg:flex"
          style={{ zIndex: 10 }}
        />
        <div>{children}</div>
      </body>
    </html>
  );
}
