import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import clsx from "clsx";
import "@/styles/global.scss";
import { Navbar } from "@/components/navbar/navbar";

const akira = localFont({
  src: "../fonts/Akira.otf",
  variable: "--font-akira"
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(akira.variable, inter.variable)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
