// scripts/generate-sprite.ts
import { readdir, readFile, writeFile, mkdir, stat } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

async function getAllSvgFiles(dir: string, baseDir: string = dir): Promise<Array<{ path: string; name: string }>> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: Array<{ path: string; name: string }> = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      // Recursively get SVG files from subdirectories
      const subFiles = await getAllSvgFiles(fullPath, baseDir);
      files.push(...subFiles);
    } else if (entry.name.endsWith('.svg')) {
      // Generate icon name from relative path
      const name = entry.name.replace('.svg', '').replace(/\//g, '-');
      files.push({ path: fullPath, name });
    }
  }

  return files;
}

async function generateSprite() {
  const iconsDir = join(process.cwd(), 'src/assets');
  const publicDir = join(process.cwd(), 'public');
  const typesDir = join(process.cwd(), 'src/types');

  // Ensure directories exist
  if (!existsSync(publicDir)) await mkdir(publicDir, { recursive: true });
  if (!existsSync(typesDir)) await mkdir(typesDir, { recursive: true });

  // Read all SVG files recursively
  const svgFiles = await getAllSvgFiles(iconsDir);

  if (svgFiles.length === 0) {
    console.warn('⚠️  No SVG files found in assets/icons');
    return;
  }

  let sprite = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none">\n';
  const iconNames: string[] = [];

  for (const file of svgFiles) {
    iconNames.push(file.name);

    const content = await readFile(file.path, 'utf-8');

    // Extract viewBox if it exists
    const viewBoxMatch = content.match(/viewBox="([^"]+)"/);
    const viewBox = viewBoxMatch ? ` viewBox="${viewBoxMatch[1]}"` : '';

    // Remove SVG wrapper and convert to symbol
    const innerContent = content
      .replace(/<svg[^>]*>/, '')
      .replace('</svg>', '')
      .trim();

    sprite += `  <symbol id="${file.name}"${viewBox}>\n`;
    sprite += `    ${innerContent}\n`;
    sprite += `  </symbol>\n`;
  }

  sprite += '</svg>';

  // Write sprite to public folder
  await writeFile(join(publicDir, 'sprite.svg'), sprite);

  // Generate TypeScript types
  const types = `// Auto-generated by scripts/generate-sprite.ts
// Do not edit manually

export type IconName =
${iconNames.map(n => `  | '${n}'`).join('\n')};

export const iconNames: IconName[] = [
${iconNames.map(n => `  '${n}',`).join('\n')}
];
`;

  await writeFile(join(typesDir, 'icons.ts'), types);

  console.log(`✅ Generated sprite with ${iconNames.length} icons`);
  console.log(`📦 Output: public/sprite.svg`);
  console.log(`📝 Types: types/icons.ts`);
}

generateSprite().catch(console.error);
